version: "3.7"
services:
  
  app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      secretKey: default-secret-key
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 2qazxsw
      DATABASE_NAME: Quiz_Users
      DATABASE_HOST: db
    command: ["nodemon", "app.js"]
    ports:
      - 3000:300
    networks:
      - frontend
      - backend

  db:
    image: postgres
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: Quiz_Users
      POSTGRES_PASSWORD: 2qazxsw
    networks:
      - tools
      - backend

  adminer:
    image: adminer
    restart: on-failure
    ports: 
      - 8080:80
    networks:
      - tools
      - backend

volumes:
  db-storage:
  node_modules:

networks:
  backend:
  frontend:
  tools:
